version: 2
jobs:
  build:
    working_directory: ~/ng
    docker:
      - image: angular/ngcontainer:0.0.1
    steps:
      - checkout

      - restore_cache:
          key: angular_bazel_example-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: bazel info release
      - run: bazel run @yarn//:yarn
      - run: bazel --bazelrc=docker.bazelrc build ...

      - save_cache:
          key: angular_bazel_example-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"